name: Configure Repository Settings

on:
  push:
    branches:
      - main

jobs:
  configure:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      pull-requests: write
      repository-projects: read
    steps:
      - name: Configurer les paramètres du dépôt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -sSf -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }} \
            -d '{"description": "Nouvelle description", "private": false}'
