name: Configure Repository Settings

on:
  push:
    branches:
      - main

jobs:
  configure:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write
    #   issues: read
    #   pull-requests: write
    #   repository-projects: read
    steps:
      - name: Configurer les paramètres du dépôt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -sSf -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/branches
